const REGION_NAMES = {
  1: 'Northeast',
  2: 'Southeast',
  3: 'North Central',
  4: 'South Central',
  5: 'Northwest',
  6: 'Southwest',
};

const REGION_COLORS = {
  1: '#6366f1',   // Northeast      — indigo
  2: '#eab308',   // Southeast      — amber
  3: '#a855f7',   // North Central  — purple
  4: '#ef4444',   // South Central  — red
  5: '#3b82f6',   // Northwest      — blue
  6: '#22c55e',   // Southwest      — green
};

const CLUBS = [
  // Region 1 – Northeast
  { id: 'SHOT', name: 'Sight Hound Organization of Tidewater', city: 'Dendron', state: 'VA', lat: 37.048, lng: -76.950, org: ['ASFA', 'AKC'], region: 1, website: 'https://shotlurecoursing.org' },
  { id: 'TSSC', name: 'Tri-State Sighthound Club', city: 'Slippery Rock', state: 'PA', lat: 41.064, lng: -80.055, org: ['ASFA'], region: 1 },
  { id: 'CHAMP', name: 'Chesapeake Area Members Pack', city: 'Leesburg', state: 'VA', lat: 39.115, lng: -77.563, org: ['ASFA'], region: 1, website: 'https://www.facebook.com/groups/4034246756586391/' },
  { id: 'UCBSC', name: 'Upper Chesapeake Bay Saluki Club', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: ['ASFA'], region: 1, website: 'https://hanoverlurecoursingclubs.com' },
  { id: 'MDIHC', name: 'Mason-Dixon Ibizan Hound Club', city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: ['ASFA', 'AKC'], region: 1, website: 'https://hanoverlurecoursingclubs.com' },
  { id: 'THLC', name: 'Tortoise & Hare Lure Coursers', city: 'Littlestown', state: 'PA', lat: 39.745, lng: -76.925, org: ['ASFA', 'AKC'], region: 1, website: 'https://hanoverlurecoursingclubs.com' },
  { id: 'GONE', name: 'Gazehounds of New England', city: 'Blandford', state: 'MA', lat: 42.149, lng: -72.944, org: ['ASFA', 'AKC'], region: 1, website: 'https://gazehoundsofnewengland.org' },
  { id: 'CLCNY', name: 'Lake Country Lure Coursers', city: 'Fredonia', state: 'NY', lat: 42.441, lng: -79.335, org: ['ASFA'], region: 1, website: 'https://lakecountrylurecoursers.com' },

  // Region 2 – Southeast
  { id: 'GASM', name: 'Gazehound Association of the Smoky Mountains', city: 'Limestone', state: 'TN', lat: 36.496, lng: -82.628, org: ['ASFA', 'LGRA'], region: 2, website: 'https://gasm.club' },
  { id: 'LEGS', name: 'Lure Enthusiasts of Georgia Sighthounds', city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: ['ASFA'], region: 2, website: 'https://legscoursing.com' },
  { id: 'BaCOA', name: 'Basenji Club of America', city: 'Shelbyville', state: 'TN', lat: 35.482, lng: -86.459, org: ['ASFA', 'AKC'], region: 2 },
  { id: 'BKC', name: 'Black Knights Coursing', city: 'Pass Christian', state: 'MS', lat: 30.321, lng: -89.251, org: ['AKC'], region: 2, website: 'https://blackknightscoursing.com' },
  { id: 'CFSRC', name: 'Central Florida Sighthound Racing Club', city: 'Williston', state: 'FL', lat: 29.387, lng: -82.449, org: ['ASFA', 'LGRA'], region: 2, website: 'https://www.facebook.com/groups/714718341874468' },

  // Region 3 – North Central
  { id: 'ICA', name: 'Iowa Coursing Association', city: 'Des Moines', state: 'IA', lat: 41.588, lng: -93.620, org: ['ASFA', 'AKC', 'LGRA'], region: 3, website: 'https://www.facebook.com/groups/IowaCoursingAssociation/' },
  { id: 'MCA', name: 'Minnesota Coursing Association', city: 'Farmington', state: 'MN', lat: 44.647, lng: -93.149, org: ['ASFA', 'AKC'], region: 3, website: 'https://www.facebook.com/groups/minnesotacoursingassociation/' },
  { id: 'GTCWC', name: 'Greater Twin Cities Whippet Club', city: 'Farmington', state: 'MN', lat: 44.657, lng: -93.139, org: ['ASFA'], region: 3 },
  { id: 'NCA', name: 'Nebraska Coursing Association', city: 'Omaha', state: 'NE', lat: 41.261, lng: -95.937, org: ['ASFA'], region: 3 },
  { id: 'HCA', name: 'Heartland Coursing Association', city: 'Auburn', state: 'KS', lat: 38.902, lng: -95.800, org: ['ASFA', 'LGRA'], region: 3, website: 'https://www.facebook.com/groups/770647583032489/' },
  { id: 'IHCUS', name: 'Ibizan Hound Club of the United States', city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: ['ASFA', 'AKC'], region: 3 },
  { id: 'BCOA', name: 'Borzoi Club of America', city: 'Manley', state: 'NE', lat: 40.921, lng: -96.171, org: ['ASFA', 'AKC', 'LGRA'], region: 3 },
  { id: 'MBC', name: 'Midwest Borzoi Club', city: 'Lima', state: 'OH', lat: 40.742, lng: -84.105, org: ['ASFA', 'AKC'], region: 3 },
  { id: 'MGA', name: 'Michigan Gazehound Association', city: 'Rockwood', state: 'MI', lat: 42.071, lng: -83.246, org: ['ASFA', 'AKC'], region: 3 },
  { id: 'MWCC', name: 'Midwest Coursing Club', city: 'Caledonia', state: 'WI', lat: 42.786, lng: -87.866, org: ['ASFA', 'AKC'], region: 3 },
  { id: 'OKIGO', name: 'Ohio, Kentucky, Indiana Gazehound Organization', city: 'Yellow Springs', state: 'OH', lat: 39.800, lng: -83.887, org: ['ASFA', 'AKC'], region: 3, website: 'https://www.facebook.com/groups/713639960503813/' },
  { id: 'SLASH', name: 'Saint Louis Area Sighthounds', city: 'Dix', state: 'IL', lat: 38.447, lng: -88.952, org: ['ASFA', 'LGRA'], region: 3, website: 'http://www.slashcoursing.org' },
  { id: 'IWCA', name: 'Irish Wolfhound Club of America', city: 'Gray Summit', state: 'MO', lat: 38.411, lng: -90.774, org: ['ASFA', 'AKC', 'LGRA'], region: 3, website: 'https://iwclubofamerica.org' },
  { id: 'SCOA', name: 'Saluki Club of America', city: 'Gray Summit', state: 'MO', lat: 38.421, lng: -90.764, org: ['ASFA', 'AKC'], region: 3, website: 'https://salukiclub.org' },

  // Region 4 – South Central
  { id: 'CLCA', name: 'Colorado Lure Coursing Association', city: 'Peyton', state: 'CO', lat: 38.932, lng: -104.296, org: ['ASFA', 'LGRA'], region: 4, website: 'https://clcaonline.com' },
  { id: 'LLCC', name: 'Llano Lure Coursing Club', city: 'Estancia', state: 'NM', lat: 34.760, lng: -106.056, org: ['ASFA'], region: 4 },
  { id: 'RMIWA', name: 'Rocky Mountain Irish Wolfhound Association', city: 'Bennett', state: 'CO', lat: 39.750, lng: -104.430, org: ['ASFA'], region: 4, website: 'https://rmiwa.org' },
  { id: 'ORCA', name: 'Oklahoma Racing & Coursing Association', city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: ['ASFA', 'AKC', 'LGRA'], region: 4 },

  // Region 5 – Northwest
  { id: 'WWWA', name: 'Western Washington Whippet Association', city: 'Monroe', state: 'WA', lat: 47.855, lng: -121.971, org: ['ASFA', 'AKC', 'LGRA'], region: 5, website: 'https://wwwhippet.org' },
  { id: 'SISFA', name: 'Southern Idaho Sighthound Field Association', city: 'Emmett', state: 'ID', lat: 43.874, lng: -116.499, org: ['ASFA'], region: 5 },
  { id: 'SWEPT', name: 'Silken Windhounds for Endurance, Performance & Training', city: 'Damascus', state: 'OR', lat: 45.413, lng: -122.434, org: ['ASFA', 'LGRA'], region: 5 },
  { id: 'AWC', name: 'American Whippet Club', city: 'Pasco', state: 'WA', lat: 46.239, lng: -119.100, org: ['ASFA', 'AKC'], region: 5, website: 'https://americanwhippetclub.net' },

  // Region 6 – Southwest
  { id: 'NCIWC', name: 'Northern California Irish Wolfhound Club', city: 'Woodland', state: 'CA', lat: 38.679, lng: -121.773, org: ['ASFA', 'AKC'], region: 6, website: 'https://nciwc.org' },
  { id: 'SWC', name: 'Silken Windhounds of California', city: 'Elverta', state: 'CA', lat: 38.713, lng: -121.406, org: ['ASFA', 'LGRA'], region: 6, website: 'https://casilkenwindhound.com' },
  { id: 'USRCC', name: 'Utah Sighthound Racing & Coursing Club', city: 'South Jordan', state: 'UT', lat: 40.560, lng: -111.929, org: ['ASFA', 'AKC', 'LGRA'], region: 6, website: 'https://utahsighthounds.org' },
  { id: 'CCASH', name: 'Central Coast Association of Sighthounds', city: 'Arroyo Grande', state: 'CA', lat: 35.118, lng: -120.590, org: ['ASFA', 'LGRA'], region: 6 },
  { id: 'CCA', name: 'California Coursing Association', city: 'Chino Hills', state: 'CA', lat: 33.993, lng: -117.729, org: ['ASFA', 'AKC'], region: 6 },
  { id: 'OCRRC', name: 'Orange Coast Rhodesian Ridgeback Club', city: 'Chino Hills', state: 'CA', lat: 33.983, lng: -117.739, org: ['ASFA', 'AKC'], region: 6, website: 'https://ocrrc.com' },
  { id: 'DFB', name: 'Desert Fun Bunch', city: 'Phoenix', state: 'AZ', lat: 33.449, lng: -112.073, org: ['AKC'], region: 6, website: 'https://desertfunbunch.org' },
  { id: 'RACE', name: 'Racing and Coursing Enthusiasts', city: 'Sacramento', state: 'CA', lat: 38.575, lng: -121.487, org: ['ASFA', 'LGRA'], region: 6, website: 'https://aok9racing.com' },

  // LGRA clubs
  { id: 'CSA', name: 'Cascadia Sighthound Association', city: 'Snohomish', state: 'WA', lat: 47.910, lng: -122.099, org: ['LGRA'], region: 5 },
  { id: 'PNR', name: 'Pacific Northwest Racing', city: 'Auburn', state: 'WA', lat: 47.307, lng: -122.229, org: ['LGRA'], region: 5 },
  { id: 'PARC', name: 'Pacific All-breed Racing Club', city: 'Canby', state: 'OR', lat: 45.263, lng: -122.693, org: ['LGRA'], region: 5 },
  { id: 'GWWA', name: 'Great Western Whippet Association', city: 'Woodland', state: 'CA', lat: 38.679, lng: -121.773, org: ['LGRA'], region: 6 },
  { id: 'NCWC', name: 'Northern California Whippet Club', city: 'Rancho Murieta', state: 'CA', lat: 38.524, lng: -121.104, org: ['LGRA'], region: 6 },
  { id: 'NFH', name: "Northstate Flyin' Hounds", city: 'Chico', state: 'CA', lat: 39.728, lng: -121.837, org: ['LGRA'], region: 6 },
  { id: 'RWRG', name: 'Reata Whippet Racing Group', city: 'Bakersfield', state: 'CA', lat: 35.373, lng: -119.019, org: ['LGRA'], region: 6 },
  { id: 'RCRA', name: 'River City Racing Association', city: 'Sacramento', state: 'CA', lat: 38.575, lng: -121.487, org: ['LGRA'], region: 6 },
  { id: 'TTBC', name: 'Turquoise Trail Borzoi Club', city: 'Albuquerque', state: 'NM', lat: 35.085, lng: -106.651, org: ['LGRA'], region: 4 },
  { id: 'SCWA', name: 'Southern California Whippet Association', city: 'Los Angeles', state: 'CA', lat: 34.052, lng: -118.244, org: ['LGRA'], region: 6 },
  { id: 'BCSEW', name: 'Basenji Club of Southeast Wisconsin', city: 'Waukesha', state: 'WI', lat: 43.011, lng: -88.231, org: ['LGRA'], region: 3 },
  { id: 'DARK', name: 'Detroit Area Racing Klub', city: 'Detroit', state: 'MI', lat: 42.332, lng: -83.043, org: ['LGRA'], region: 3 },
  { id: 'GCWC', name: 'Greater Chicago Whippet Club', city: 'Chicago', state: 'IL', lat: 41.850, lng: -87.650, org: ['LGRA'], region: 3 },
  { id: 'LARK', name: 'Lorain Area Racing Klub', city: 'Lorain', state: 'OH', lat: 41.453, lng: -82.182, org: ['LGRA'], region: 3 },
  { id: 'NARC', name: 'Northland Amateur Racing Club', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: ['LGRA'], region: 3 },
  { id: 'CBRA', name: 'Count Basie Racing Association', city: 'Red Bank', state: 'NJ', lat: 40.347, lng: -74.073, org: ['LGRA'], region: 1 },
  { id: 'GSG', name: 'Granite State Greyhounds', city: 'Bow', state: 'NH', lat: 43.114, lng: -71.534, org: ['LGRA'], region: 1 },
  { id: 'IWADEV', name: 'Irish Wolfhound Association of Delaware Valley', city: 'Malvern', state: 'PA', lat: 40.036, lng: -75.513, org: ['LGRA'], region: 1 },
  { id: 'LVCC', name: 'Lehigh Valley Coursing Club', city: 'Allentown', state: 'PA', lat: 40.608, lng: -75.490, org: ['AKC', 'LGRA'], region: 1 },
  { id: 'MAIGC', name: 'Mid-Atlantic Italian Greyhound Club', city: 'Cherry Hill', state: 'NJ', lat: 39.935, lng: -75.019, org: ['LGRA'], region: 1 },
  { id: 'PVBC', name: 'Potomac Valley Borzoi Club', city: 'Gaithersburg', state: 'MD', lat: 39.143, lng: -77.201, org: ['LGRA'], region: 1 },
  { id: 'GIT', name: 'Gazehounds in Texas', city: 'Austin', state: 'TX', lat: 30.267, lng: -97.743, org: ['LGRA'], region: 4 },
  { id: 'SOTL', name: 'Sighthounds on the Lam', city: 'Spartanburg', state: 'SC', lat: 34.950, lng: -81.932, org: ['LGRA'], region: 2 },
  { id: 'SOS', name: 'Southernmost Sighthounds', city: 'Key West', state: 'FL', lat: 24.555, lng: -81.780, org: ['LGRA'], region: 2 },
  { id: 'SSARA', name: "Shi'Rayan Sloughis Amateur Racing Association", city: 'Crescent', state: 'IA', lat: 41.364, lng: -95.855, org: ['LGRA'], region: 3 },
  { id: 'TSWA', name: 'Tri-State Whippet Association', city: 'Louisville', state: 'KY', lat: 38.252, lng: -85.759, org: ['LGRA'], region: 3 },

  // AKC clubs
  { id: 'SSRRC', name: 'Sunshine State Rhodesian Ridgeback Club', city: 'Weirsdale', state: 'FL', lat: 29.054, lng: -81.930, org: ['AKC'], region: 2 },
  { id: 'NCWFA', name: 'Northern California Whippet Fanciers Association', city: 'Elverta', state: 'CA', lat: 38.714, lng: -121.407, org: ['AKC'], region: 6 },
  { id: 'AHCD', name: 'Afghan Hound Club of Dallas', city: 'Celina', state: 'TX', lat: 33.300, lng: -96.778, org: ['AKC'], region: 4 },
  { id: 'NTSC', name: 'North Texas Saluki Club', city: 'Celina', state: 'TX', lat: 33.305, lng: -96.775, org: ['AKC'], region: 4 },
  { id: 'GOGLCA', name: 'Greater Ocala-Gainesville Lure Coursing Association', city: 'Brooksville', state: 'FL', lat: 28.558, lng: -82.386, org: ['AKC'], region: 2 },
  { id: 'AAWC', name: 'Alamo Area Whippet Club', city: 'Angleton', state: 'TX', lat: 29.170, lng: -95.431, org: ['AKC'], region: 4 },
  { id: 'ARRC', name: 'Arizona Rhodesian Ridgeback Club', city: 'Tonopah', state: 'AZ', lat: 33.574, lng: -112.938, org: ['AKC'], region: 6 },
  { id: 'EBC', name: 'Evergreen Basenji Club', city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: ['AKC'], region: 5 },
  { id: 'LOBO', name: 'Lobo Lure Coursing Club', city: 'Santa Fe', state: 'NM', lat: 35.687, lng: -105.938, org: ['AKC'], region: 4 },
  { id: 'SSIH', name: 'Sierra Slopes Ibizan Hounds', city: 'Elverta', state: 'CA', lat: 38.715, lng: -121.408, org: ['AKC'], region: 6 },
  { id: 'NWRRC', name: 'Northwest Rhodesian Ridgeback Club', city: 'Ethel', state: 'WA', lat: 46.520, lng: -122.350, org: ['AKC'], region: 5 },
  { id: 'AHCAU', name: 'Afghan Hound Club of Austin', city: 'Florence', state: 'TX', lat: 30.845, lng: -97.792, org: ['AKC'], region: 4 },
  { id: 'IWAGS', name: 'Irish Wolfhound Association of the Garden State', city: 'Somerset', state: 'NJ', lat: 40.498, lng: -74.487, org: ['AKC'], region: 1 },
  { id: 'TVRRCT', name: 'Trinity Valley Rhodesian Ridgeback Club of Texas', city: 'Ponder', state: 'TX', lat: 33.177, lng: -97.276, org: ['AKC'], region: 4 },
  { id: 'GVFRRC', name: 'Greater Valley Forge Rhodesian Ridgeback Club', city: 'Bridgewater', state: 'NJ', lat: 40.595, lng: -74.617, org: ['AKC'], region: 1 },
  { id: 'WWHA', name: 'Western Washington Hound Association', city: 'Ethel', state: 'WA', lat: 46.522, lng: -122.352, org: ['AKC'], region: 5 },
  { id: 'GCHC', name: 'Gulf Coast Hound Club', city: 'Semmes', state: 'AL', lat: 30.791, lng: -88.244, org: ['AKC'], region: 2 },
  { id: 'SDCA', name: 'Scottish Deerhound Club of America', city: 'Rockwood', state: 'PA', lat: 39.907, lng: -79.162, org: ['AKC'], region: 1 },
  { id: 'CKC', name: 'Chintimini Kennel Club', city: 'Cottage Grove', state: 'OR', lat: 43.797, lng: -123.059, org: ['AKC'], region: 5 },
  { id: 'SCIHC', name: 'Southern California Ibizan Hound Club', city: 'Helena', state: 'MT', lat: 46.596, lng: -112.027, org: ['AKC'], region: 5 },
  { id: 'RMHAC', name: 'Rocky Mountain Hound Association of Colorado', city: 'Peyton', state: 'CO', lat: 38.933, lng: -104.298, org: ['AKC'], region: 4 },
  { id: 'GCA', name: 'Greyhound Club of America', city: 'Hyde Park', state: 'UT', lat: 41.794, lng: -111.817, org: ['AKC'], region: 6 },
  { id: 'PHCA', name: 'Pharaoh Hound Club of America', city: 'Bennett', state: 'CO', lat: 39.751, lng: -104.431, org: ['AKC'], region: 4 },
  { id: 'AHGA', name: 'Alaska Hound Group Association', city: 'Palmer', state: 'AK', lat: 61.598, lng: -149.110, org: ['AKC'], region: 5 },
  { id: 'CSBC', name: 'Copper State Basenji Club', city: 'Lakeside', state: 'AZ', lat: 34.172, lng: -109.982, org: ['AKC'], region: 6 },
  { id: 'SANE', name: 'Saluki Association of New England', city: 'Blandford', state: 'MA', lat: 42.150, lng: -72.942, org: ['AKC'], region: 1 },
  { id: 'RRCUS', name: 'Rhodesian Ridgeback Club of the United States', city: "Lee's Summit", state: 'MO', lat: 38.910, lng: -94.382, org: ['AKC'], region: 3 },
  { id: 'GANG', name: 'Greyhound Association of North Georgia', city: 'Canon', state: 'GA', lat: 34.363, lng: -83.134, org: ['AKC'], region: 2 },
  { id: 'CBARRC', name: 'Chesapeake Bay Area Rhodesian Ridgeback Club', city: 'Hanover', state: 'PA', lat: 39.800, lng: -76.982, org: ['AKC'], region: 1 },
  { id: 'IWALE', name: 'Irish Wolfhound Association of Lake Erie', city: 'Fredonia', state: 'NY', lat: 42.441, lng: -79.335, org: ['AKC'], region: 1 },
];

const EVENTS = [
  // April 2026
  { id: 1, abbr: 'ICA', clubName: 'Iowa Coursing Association', name: 'ASFA Trial', startDate: '2026-04-04', endDate: null, city: 'Des Moines', state: 'IA', lat: 41.588, lng: -93.620, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 2, abbr: 'LLCC', clubName: 'Llano Lure Coursing Club', name: 'ASFA Trial', startDate: '2026-04-04', endDate: '2026-04-05', city: 'Estancia', state: 'NM', lat: 34.760, lng: -106.056, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 3, abbr: 'GASM', clubName: 'Gazehound Association of the Smoky Mountains', name: 'ASFA Trial', startDate: '2026-04-04', endDate: '2026-04-05', city: 'Limestone', state: 'TN', lat: 36.496, lng: -82.628, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 4, abbr: 'MBC', clubName: 'Midwest Borzoi Club', name: 'ASFA Trial', startDate: '2026-04-04', endDate: '2026-04-05', city: 'Lima', state: 'OH', lat: 40.742, lng: -84.105, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 5, abbr: 'SHOT', clubName: 'Sight Hound Organization of Tidewater', name: 'ASFA Trial', startDate: '2026-04-04', endDate: '2026-04-05', city: 'Dendron', state: 'VA', lat: 37.048, lng: -76.950, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 6, abbr: 'HCA', clubName: 'Heartland Coursing Association', name: 'ASFA Trial', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Auburn', state: 'KS', lat: 38.902, lng: -95.800, org: 'ASFA', isSpecialty: false, isCancelled: true },
  { id: 7, abbr: 'AWC', clubName: 'American Whippet Club', name: 'AWC National Specialty', startDate: '2026-04-11', endDate: null, city: 'Pasco', state: 'WA', lat: 46.239, lng: -119.100, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 8, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'ASFA Trial', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Waterford', state: 'CT', lat: 41.352, lng: -72.147, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 9, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'ASFA Trial', startDate: '2026-04-18', endDate: '2026-04-19', city: 'Goshen', state: 'UT', lat: 39.960, lng: -112.010, org: 'ASFA', isSpecialty: false, isCancelled: true },
  { id: 10, abbr: 'CLCA', clubName: 'Colorado Lure Coursing Association', name: 'ASFA Trial', startDate: '2026-04-25', endDate: '2026-04-26', city: 'Peyton', state: 'CO', lat: 38.932, lng: -104.296, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 11, abbr: 'MCA', clubName: 'Minnesota Coursing Association', name: 'ASFA Trial', startDate: '2026-04-25', endDate: '2026-04-26', city: 'Farmington', state: 'MN', lat: 44.647, lng: -93.149, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 12, abbr: 'TSSC', clubName: 'Tri-State Sighthound Club', name: 'ASFA Trial', startDate: '2026-04-25', endDate: '2026-04-26', city: 'Slippery Rock', state: 'PA', lat: 41.064, lng: -80.055, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 13, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'ASFA Trial', startDate: '2026-04-25', endDate: '2026-04-26', city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // May 2026
  { id: 14, abbr: 'SISFA', clubName: 'Southern Idaho Sighthound Field Association', name: 'ASFA Trial', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Emmett', state: 'ID', lat: 43.874, lng: -116.499, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 15, abbr: 'ICA', clubName: 'Iowa Coursing Association', name: 'ASFA Trial', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 16, abbr: 'CHAMP', clubName: 'Chesapeake Area Members Pack', name: 'ASFA Trial', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Leesburg', state: 'VA', lat: 39.115, lng: -77.563, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 17, abbr: 'BCOA', clubName: 'Borzoi Club of America', name: 'BCOA National Specialty', startDate: '2026-05-09', endDate: null, city: 'Manley', state: 'NE', lat: 40.921, lng: -96.171, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 18, abbr: 'GTCWC', clubName: 'Greater Twin Cities Whippet Club', name: 'ASFA Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Farmington', state: 'MN', lat: 44.657, lng: -93.139, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 19, abbr: 'MGA', clubName: 'Michigan Gazehound Association', name: 'ASFA Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Rockwood', state: 'MI', lat: 42.071, lng: -83.246, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 20, abbr: 'ORCA', clubName: 'Oklahoma Racing & Coursing Association', name: 'ASFA Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 22, abbr: 'CLCA', clubName: 'Colorado Lure Coursing Association', name: 'ASFA Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Peyton', state: 'CO', lat: 38.932, lng: -104.296, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 23, abbr: 'MWCC', clubName: 'Midwest Coursing Club', name: 'ASFA Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Caledonia', state: 'WI', lat: 42.786, lng: -87.866, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 24, abbr: 'MCA', clubName: 'Minnesota Coursing Association', name: 'ASFA Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Waverly', state: 'MN', lat: 45.074, lng: -94.002, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 25, abbr: 'IWCA', clubName: 'Irish Wolfhound Club of America', name: 'IWCA National Specialty', startDate: '2026-05-21', endDate: null, city: 'Gray Summit', state: 'MO', lat: 38.411, lng: -90.774, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 26, abbr: 'IHCUS', clubName: 'Ibizan Hound Club of the United States', name: 'ASFA Trial', startDate: '2026-05-22', endDate: null, city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 27, abbr: 'IHCUS', clubName: 'Ibizan Hound Club of the United States', name: 'IHCUS National Specialty', startDate: '2026-05-23', endDate: null, city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 28, abbr: 'CCASH', clubName: 'Central Coast Association of Sighthounds', name: 'ASFA Trial', startDate: '2026-05-23', endDate: null, city: 'Arroyo Grande', state: 'CA', lat: 35.118, lng: -120.590, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 29, abbr: 'WWWA', clubName: 'Western Washington Whippet Association', name: 'ASFA Trial', startDate: '2026-05-25', endDate: null, city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 30, abbr: 'CCA', clubName: 'California Coursing Association', name: 'ASFA Trial', startDate: '2026-05-30', endDate: '2026-05-31', city: 'Chino Hills', state: 'CA', lat: 33.993, lng: -117.729, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // June 2026
  { id: 31, abbr: 'SCOA', clubName: 'Saluki Club of America', name: 'SCOA National Specialty', startDate: '2026-06-01', endDate: null, city: 'Gray Summit', state: 'MO', lat: 38.421, lng: -90.764, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 32, abbr: 'NCA', clubName: 'Nebraska Coursing Association', name: 'ASFA Trial', startDate: '2026-06-06', endDate: '2026-06-07', city: 'Omaha', state: 'NE', lat: 41.261, lng: -95.937, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 33, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'ASFA Trial', startDate: '2026-06-06', endDate: '2026-06-07', city: 'Blandford', state: 'MA', lat: 42.149, lng: -72.944, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 34, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'ASFA Trial', startDate: '2026-06-13', endDate: '2026-06-14', city: 'Chino Hills', state: 'CA', lat: 33.983, lng: -117.739, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 35, abbr: 'MWCC', clubName: 'Midwest Coursing Club', name: 'MWCC Specialty', startDate: '2026-06-20', endDate: '2026-06-21', city: 'Caledonia', state: 'WI', lat: 42.786, lng: -87.866, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 36, abbr: 'SWEPT', clubName: 'Silken Windhounds for Endurance, Performance & Training', name: 'ASFA Trial', startDate: '2026-06-28', endDate: null, city: 'Damascus', state: 'OR', lat: 45.413, lng: -122.434, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // July 2026
  { id: 37, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-07-04', endDate: '2026-07-05', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 38, abbr: 'SWEPT', clubName: 'Silken Windhounds for Endurance, Performance & Training', name: 'ASFA Trial', startDate: '2026-07-05', endDate: null, city: 'Damascus', state: 'OR', lat: 45.413, lng: -122.434, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 39, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-07-18', endDate: '2026-07-19', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 40, abbr: 'GTCWC', clubName: 'Greater Twin Cities Whippet Club', name: 'ASFA Trial', startDate: '2026-07-18', endDate: '2026-07-19', city: 'Farmington', state: 'MN', lat: 44.657, lng: -93.139, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // August 2026
  { id: 41, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'ASFA Trial', startDate: '2026-08-01', endDate: '2026-08-02', city: 'Blandford', state: 'MA', lat: 42.149, lng: -72.944, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 42, abbr: 'MDIHC', clubName: 'Mason-Dixon Ibizan Hound Club', name: 'ASFA Trial', startDate: '2026-08-02', endDate: null, city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 43, abbr: 'SWEPT', clubName: 'Silken Windhounds for Endurance, Performance & Training', name: 'ASFA Trial', startDate: '2026-08-08', endDate: '2026-08-09', city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // September 2026
  { id: 44, abbr: 'RMIWA', clubName: 'Rocky Mountain Irish Wolfhound Association', name: 'RMIWA Specialty', startDate: '2026-09-02', endDate: null, city: 'Bennett', state: 'CO', lat: 39.750, lng: -104.430, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 45, abbr: 'MCA', clubName: 'Minnesota Coursing Association', name: 'ASFA Trial', startDate: '2026-09-05', endDate: '2026-09-06', city: 'Farmington', state: 'MN', lat: 44.647, lng: -93.149, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 46, abbr: 'SWEPT', clubName: 'Silken Windhounds for Endurance, Performance & Training', name: 'ASFA Trial', startDate: '2026-09-05', endDate: null, city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 47, abbr: 'MDIHC', clubName: 'Mason-Dixon Ibizan Hound Club', name: 'ASFA Trial', startDate: '2026-09-05', endDate: '2026-09-07', city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 48, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'Regional Invitational', startDate: '2026-09-05', endDate: null, city: 'Starkville', state: 'NY', lat: 42.920, lng: -74.210, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 49, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'ASFA Trial', startDate: '2026-09-06', endDate: null, city: 'Starkville', state: 'NY', lat: 42.920, lng: -74.210, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 50, abbr: 'OKIGO', clubName: 'Ohio, Kentucky, Indiana Gazehound Organization', name: 'Regional Invitational VI', startDate: '2026-09-12', endDate: null, city: 'Yellow Springs', state: 'OH', lat: 39.800, lng: -83.887, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 51, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'ASFA Trial', startDate: '2026-09-12', endDate: '2026-09-13', city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 52, abbr: 'OKIGO', clubName: 'Ohio, Kentucky, Indiana Gazehound Organization', name: 'ASFA Trial', startDate: '2026-09-13', endDate: null, city: 'Yellow Springs', state: 'OH', lat: 39.800, lng: -83.887, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 53, abbr: 'GTCWC', clubName: 'Greater Twin Cities Whippet Club', name: 'ASFA Trial', startDate: '2026-09-19', endDate: '2026-09-20', city: 'Farmington', state: 'MN', lat: 44.657, lng: -93.139, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 55, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'ASFA Trial', startDate: '2026-09-26', endDate: '2026-09-27', city: 'South Jordan', state: 'UT', lat: 40.560, lng: -111.929, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 56, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-09-26', endDate: '2026-09-27', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // October 2026
  { id: 57, abbr: 'ICA', clubName: 'Iowa Coursing Association', name: 'ASFA Trial', startDate: '2026-10-03', endDate: '2026-10-04', city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 58, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'Regional Invitational VII', startDate: '2026-10-03', endDate: null, city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 59, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'ASFA Trial', startDate: '2026-10-04', endDate: null, city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 60, abbr: 'BaCOA', clubName: 'Basenji Club of America', name: 'BaCOA National Specialty', startDate: '2026-10-04', endDate: null, city: 'Shelbyville', state: 'TN', lat: 35.482, lng: -86.459, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 61, abbr: 'NCIWC', clubName: 'Northern California Irish Wolfhound Club', name: 'NCIWC Specialty', startDate: '2026-10-09', endDate: null, city: 'Woodland', state: 'CA', lat: 38.679, lng: -121.773, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 62, abbr: 'MCA', clubName: 'Minnesota Coursing Association', name: 'ASFA Trial', startDate: '2026-10-10', endDate: '2026-10-11', city: 'Waverly', state: 'MN', lat: 45.074, lng: -94.002, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 63, abbr: 'MBC', clubName: 'Midwest Borzoi Club', name: 'ASFA Trial', startDate: '2026-10-16', endDate: null, city: 'Dix', state: 'IL', lat: 38.447, lng: -88.952, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 64, abbr: 'MGA', clubName: 'Michigan Gazehound Association', name: 'ASFA Trial', startDate: '2026-10-17', endDate: '2026-10-18', city: 'Rockwood', state: 'MI', lat: 42.071, lng: -83.246, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 65, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'USRCC Specialty', startDate: '2026-10-17', endDate: '2026-10-18', city: 'South Jordan', state: 'UT', lat: 40.560, lng: -111.929, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 66, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'ASFA Trial', startDate: '2026-10-17', endDate: '2026-10-18', city: 'Griswold', state: 'CT', lat: 41.565, lng: -71.962, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 67, abbr: 'SLASH', clubName: 'Sighthound Lure Association of the Southern Heartland', name: 'ASFA Trial', startDate: '2026-10-17', endDate: '2026-10-18', city: 'Dix', state: 'IL', lat: 38.447, lng: -88.952, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 68, abbr: 'HCA', clubName: 'Heartland Coursing Association', name: 'Regional Invitational V', startDate: '2026-10-18', endDate: null, city: 'Kansas City', state: 'MO', lat: 39.099, lng: -94.578, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 69, abbr: 'HCA', clubName: 'Heartland Coursing Association', name: 'ASFA Trial', startDate: '2026-10-24', endDate: '2026-10-25', city: 'Auburn', state: 'KS', lat: 38.902, lng: -95.800, org: 'ASFA', isSpecialty: false, isCancelled: true },
  { id: 70, abbr: 'ASFA', clubName: 'ASFA International', name: 'ASFA International Invitational', startDate: '2026-10-24', endDate: '2026-10-25', city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 71, abbr: 'NCA', clubName: 'Nebraska Coursing Association', name: 'ASFA Trial', startDate: '2026-10-31', endDate: null, city: 'Omaha', state: 'NE', lat: 41.261, lng: -95.937, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // November 2026
  { id: 72, abbr: 'NCA', clubName: 'Nebraska Coursing Association', name: 'ASFA Trial', startDate: '2026-11-01', endDate: null, city: 'Omaha', state: 'NE', lat: 41.261, lng: -95.937, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 73, abbr: 'LLCC', clubName: 'Llano Lure Coursing Club', name: 'ASFA Trial', startDate: '2026-11-07', endDate: '2026-11-08', city: 'Santa Fe', state: 'NM', lat: 35.687, lng: -105.938, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 74, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'ASFA Trial', startDate: '2026-11-14', endDate: '2026-11-15', city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 75, abbr: 'RMIWA', clubName: 'Rocky Mountain Irish Wolfhound Association', name: 'RMIWA Specialty', startDate: '2026-11-21', endDate: '2026-11-22', city: 'Bennett', state: 'CO', lat: 39.750, lng: -104.430, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 76, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'Regional Invitational X', startDate: '2026-11-27', endDate: null, city: 'Chino Hills', state: 'CA', lat: 33.983, lng: -117.739, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 77, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-11-27', endDate: '2026-11-29', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // December 2026
  { id: 78, abbr: 'TSSC', clubName: 'Tri-State Sighthound Club', name: 'ASFA Trial', startDate: '2026-12-05', endDate: '2026-12-06', city: 'Slippery Rock', state: 'PA', lat: 41.064, lng: -80.055, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 79, abbr: 'SLASH', clubName: 'Sighthound Lure Association of the Southern Heartland', name: 'ASFA Trial', startDate: '2026-12-27', endDate: '2026-12-28', city: 'Sorento', state: 'IL', lat: 38.988, lng: -89.570, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 80, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-12-27', endDate: '2026-12-31', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // ── Early 2026 ASFA (January–March) ──────────────────────────────────────
  { id: 81, abbr: 'DFB', clubName: 'Desert Fun Bunch', name: 'ASFA Specialty', startDate: '2026-01-17', endDate: '2026-01-18', city: 'Black Canyon City', state: 'AZ', lat: 34.065, lng: -112.125, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 82, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'ASFA Specialty', startDate: '2026-02-14', endDate: '2026-02-15', city: 'Chino Hills', state: 'CA', lat: 33.983, lng: -117.739, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 83, abbr: 'CLCA', clubName: 'Colorado Lure Coursing Association', name: 'ASFA Trial', startDate: '2026-02-21', endDate: '2026-02-22', city: 'Peyton', state: 'CO', lat: 38.932, lng: -104.296, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 84, abbr: 'DFB', clubName: 'Desert Fun Bunch', name: 'ASFA Specialty', startDate: '2026-02-21', endDate: '2026-02-22', city: 'Tonopah', state: 'AZ', lat: 33.574, lng: -112.938, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 85, abbr: 'NCIWC', clubName: 'Northern California Irish Wolfhound Club', name: 'ASFA Trial', startDate: '2026-02-28', endDate: null, city: 'Fairfield', state: 'CA', lat: 38.249, lng: -122.040, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 86, abbr: 'THLC', clubName: 'Tortoise & Hare Lure Coursers', name: 'ASFA Trial', startDate: '2026-03-07', endDate: '2026-03-08', city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 87, abbr: 'CLCA', clubName: 'Colorado Lure Coursing Association', name: 'ASFA Trial', startDate: '2026-03-14', endDate: '2026-03-15', city: 'Peyton', state: 'CO', lat: 38.932, lng: -104.296, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 88, abbr: 'SWC', clubName: 'Silken Windhounds of California', name: 'ASFA Specialty', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Elverta', state: 'CA', lat: 38.713, lng: -121.406, org: 'ASFA', isSpecialty: true, isCancelled: false },
  { id: 89, abbr: 'LEGS', clubName: 'Lure Enthusiasts of Georgia Sighthounds', name: 'ASFA Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Whitesburg', state: 'GA', lat: 33.504, lng: -84.955, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 90, abbr: 'SLASH', clubName: 'Sighthound Lure Association of the Southern Heartland', name: 'ASFA Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Sorento', state: 'IL', lat: 38.988, lng: -89.570, org: 'ASFA', isSpecialty: false, isCancelled: false },
  { id: 91, abbr: 'UCBSC', clubName: 'Upper Chesapeake Bay Saluki Club', name: 'ASFA Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'ASFA', isSpecialty: false, isCancelled: false },

  // ── AKC Lure Coursing Trials ──────────────────────────────────────────────
  { id: 92, abbr: 'DFB', clubName: 'Desert Fun Bunch', name: 'AKC Lure Coursing Trial', startDate: '2026-01-17', endDate: '2026-01-18', city: 'Black Canyon City', state: 'AZ', lat: 34.065, lng: -112.125, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 93, abbr: 'DFB', clubName: 'Desert Fun Bunch', name: 'AKC Lure Coursing Trial', startDate: '2026-02-21', endDate: '2026-02-22', city: 'Tonopah', state: 'AZ', lat: 33.574, lng: -112.938, org: 'AKC', isSpecialty: false, isCancelled: false },

  // ── AKC Fast CAT (Black Knights Coursing) ────────────────────────────────
  { id: 95, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-04-03', endDate: '2026-04-05', city: 'Fort Pierce', state: 'FL', lat: 27.447, lng: -80.326, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 96, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-04-17', endDate: '2026-04-19', city: 'Ruston', state: 'LA', lat: 32.523, lng: -92.638, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 97, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-04-24', endDate: '2026-04-26', city: 'Mesquite', state: 'TX', lat: 32.764, lng: -96.599, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 98, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-05-14', endDate: '2026-05-17', city: 'Fort Myers', state: 'FL', lat: 26.640, lng: -81.872, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 99, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-05-21', endDate: '2026-05-25', city: 'Kalamazoo', state: 'MI', lat: 42.292, lng: -85.588, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 100, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-06-05', endDate: '2026-06-07', city: 'Fort Pierce', state: 'FL', lat: 27.447, lng: -80.326, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 101, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-06-10', endDate: '2026-06-14', city: 'Tampa', state: 'FL', lat: 27.950, lng: -82.457, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 102, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-07-09', endDate: '2026-07-12', city: 'Marshall', state: 'MI', lat: 42.272, lng: -84.958, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 103, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-07-16', endDate: '2026-07-19', city: 'South Bend', state: 'IN', lat: 41.676, lng: -86.252, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 104, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-08-26', endDate: '2026-08-30', city: 'Lexington', state: 'KY', lat: 38.050, lng: -84.503, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 105, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-09-18', endDate: '2026-09-20', city: 'Greensburg', state: 'IN', lat: 39.337, lng: -85.485, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 106, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-10-09', endDate: '2026-10-12', city: 'Fort Pierce', state: 'FL', lat: 27.447, lng: -80.326, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 107, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-10-30', endDate: '2026-11-01', city: 'Columbus', state: 'IN', lat: 39.202, lng: -85.921, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 108, abbr: 'BKC', clubName: 'Black Knights Coursing', name: 'AKC Fast CAT', startDate: '2026-11-06', endDate: '2026-11-08', city: 'Denison', state: 'TX', lat: 33.755, lng: -96.537, org: 'AKC', isSpecialty: false, isCancelled: false },

  // LGRA meets — calendar may not extend to late 2026
  { id: 109, abbr: 'GASM', clubName: 'Gazehound Association of the Smoky Mountains', name: 'LGRA Meet', startDate: '2026-04-09', endDate: '2026-04-10', city: 'Limestone', state: 'TN', lat: 36.496, lng: -82.628, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 110, abbr: 'GASM', clubName: 'Gazehound Association of the Smoky Mountains', name: 'LGRA Meet', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Limestone', state: 'TN', lat: 36.496, lng: -82.628, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 111, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-04-20', endDate: '2026-04-21', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 112, abbr: 'GSG', clubName: 'Granite State Greyhounds', name: 'LGRA Meet', startDate: '2026-04-30', endDate: '2026-05-01', city: 'Bow', state: 'NH', lat: 43.114, lng: -71.534, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 113, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 114, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-06-13', endDate: '2026-06-14', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 115, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-07-11', endDate: '2026-07-12', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 116, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-09-12', endDate: '2026-09-13', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 117, abbr: 'LGRA', clubName: 'LGRA Nationals / Silkenfest', name: 'LGRA Nationals', startDate: '2026-09-23', endDate: '2026-09-29', city: 'Calhan', state: 'CO', lat: 38.742, lng: -104.296, org: 'LGRA', isSpecialty: true, isCancelled: false },
  { id: 118, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-10-17', endDate: '2026-10-18', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },
  { id: 119, abbr: 'NARC', clubName: 'Northland Amateur Racing Club', name: 'LGRA Meet', startDate: '2026-11-07', endDate: '2026-11-08', city: 'Ramsey', state: 'MN', lat: 45.256, lng: -93.451, org: 'LGRA', isSpecialty: false, isCancelled: false },

  // ── AKC Lure Coursing Trials (from AKC event search, full year) ──────────
  { id: 120, abbr: 'AAWC', clubName: 'Alamo Area Whippet Club', name: 'AKC Lure Coursing Trial', startDate: '2026-02-28', endDate: '2026-03-01', city: 'Angleton', state: 'TX', lat: 29.170, lng: -95.431, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 121, abbr: 'AHCAU', clubName: 'Afghan Hound Club of Austin', name: 'AKC Lure Coursing Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Florence', state: 'TX', lat: 30.845, lng: -97.792, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 122, abbr: 'AHCD', clubName: 'Afghan Hound Club of Dallas', name: 'AKC Lure Coursing Trial', startDate: '2026-01-17', endDate: null, city: 'Celina', state: 'TX', lat: 33.300, lng: -96.778, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 123, abbr: 'AHGA', clubName: 'Alaska Hound Group Association', name: 'AKC Lure Coursing Trial', startDate: '2026-05-30', endDate: '2026-05-31', city: 'Palmer', state: 'AK', lat: 61.598, lng: -149.110, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 124, abbr: 'AHGA', clubName: 'Alaska Hound Group Association', name: 'AKC Lure Coursing Trial', startDate: '2026-07-17', endDate: '2026-07-19', city: 'Palmer', state: 'AK', lat: 61.598, lng: -149.110, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 125, abbr: 'AHGA', clubName: 'Alaska Hound Group Association', name: 'AKC Lure Coursing Trial', startDate: '2026-09-12', endDate: '2026-09-13', city: 'Palmer', state: 'AK', lat: 61.598, lng: -149.110, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 126, abbr: 'ARRC', clubName: 'Arizona Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-07', endDate: '2026-03-08', city: 'Tonopah', state: 'AZ', lat: 33.574, lng: -112.938, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 127, abbr: 'AWC', clubName: 'American Whippet Club', name: 'AKC Lure Coursing Trial', startDate: '2026-04-12', endDate: null, city: 'Pasco', state: 'WA', lat: 46.239, lng: -119.100, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 128, abbr: 'AWC', clubName: 'American Whippet Club', name: 'AKC Lure Coursing Trial', startDate: '2026-06-26', endDate: null, city: 'Williamston', state: 'MI', lat: 42.685, lng: -84.282, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 129, abbr: 'BCOA', clubName: 'Borzoi Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-05-10', endDate: null, city: 'Weeping Water', state: 'NE', lat: 40.870, lng: -96.132, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 130, abbr: 'BaCOA', clubName: 'Basenji Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-06-26', endDate: null, city: 'Williamston', state: 'MI', lat: 42.685, lng: -84.282, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 131, abbr: 'BaCOA', clubName: 'Basenji Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-10-04', endDate: null, city: 'Shelbyville', state: 'TN', lat: 35.482, lng: -86.459, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 132, abbr: 'CBARRC', clubName: 'Chesapeake Bay Area Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-09-12', endDate: '2026-09-13', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 133, abbr: 'CCA', clubName: 'California Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-05-30', endDate: '2026-05-31', city: 'Chino', state: 'CA', lat: 33.978, lng: -117.688, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 134, abbr: 'CKC', clubName: 'Chintimini Kennel Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Cottage Grove', state: 'OR', lat: 43.797, lng: -123.059, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 135, abbr: 'CKC', clubName: 'Chintimini Kennel Club', name: 'AKC Lure Coursing Trial', startDate: '2026-09-19', endDate: '2026-09-20', city: 'Philomath', state: 'OR', lat: 44.540, lng: -123.367, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 136, abbr: 'CKC', clubName: 'Chintimini Kennel Club', name: 'AKC Lure Coursing Trial', startDate: '2026-10-10', endDate: '2026-10-11', city: 'Molalla', state: 'OR', lat: 45.146, lng: -122.576, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 137, abbr: 'CSBC', clubName: 'Copper State Basenji Club', name: 'AKC Lure Coursing Trial', startDate: '2026-08-01', endDate: '2026-08-02', city: 'Lakeside', state: 'AZ', lat: 34.172, lng: -109.982, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 138, abbr: 'EBC', clubName: 'Evergreen Basenji Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-07', endDate: '2026-03-08', city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 139, abbr: 'EBC', clubName: 'Evergreen Basenji Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Roy', state: 'WA', lat: 47.025, lng: -122.574, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 140, abbr: 'GANG', clubName: 'Greyhound Association of North Georgia', name: 'AKC Lure Coursing Trial', startDate: '2026-10-03', endDate: '2026-10-04', city: 'Canon', state: 'GA', lat: 34.363, lng: -83.134, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 141, abbr: 'GCA', clubName: 'Greyhound Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-05-17', endDate: null, city: 'Hyde Park', state: 'UT', lat: 41.794, lng: -111.817, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 142, abbr: 'GCHC', clubName: 'Gulf Coast Hound Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Semmes', state: 'AL', lat: 30.791, lng: -88.244, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 143, abbr: 'GOGLCA', clubName: 'Greater Ocala-Gainesville Lure Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-02-21', endDate: '2026-02-22', city: 'Brooksville', state: 'FL', lat: 28.558, lng: -82.386, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 144, abbr: 'GOGLCA', clubName: 'Greater Ocala-Gainesville Lure Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-03-21', endDate: '2026-03-22', city: 'Brooksville', state: 'FL', lat: 28.558, lng: -82.386, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 145, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'AKC Lure Coursing Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Waterford', state: 'CT', lat: 41.352, lng: -72.147, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 146, abbr: 'GONE', clubName: 'Gazehounds of New England', name: 'AKC Lure Coursing Trial', startDate: '2026-10-31', endDate: '2026-11-01', city: 'Ayer', state: 'MA', lat: 42.560, lng: -71.595, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 147, abbr: 'GVFRRC', clubName: 'Greater Valley Forge Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Somerset', state: 'NJ', lat: 40.498, lng: -74.487, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 148, abbr: 'GVFRRC', clubName: 'Greater Valley Forge Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-09-19', endDate: '2026-09-20', city: 'Bridgewater', state: 'NJ', lat: 40.595, lng: -74.617, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 149, abbr: 'ICA', clubName: 'Iowa Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-04-04', endDate: null, city: 'Des Moines', state: 'IA', lat: 41.588, lng: -93.620, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 150, abbr: 'ICA', clubName: 'Iowa Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-05-23', endDate: '2026-05-24', city: 'Cedar Falls', state: 'IA', lat: 42.524, lng: -92.445, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 151, abbr: 'IHCUS', clubName: 'Ibizan Hound Club of the United States', name: 'AKC Lure Coursing Trial', startDate: '2026-06-26', endDate: null, city: 'Williamston', state: 'MI', lat: 42.685, lng: -84.282, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 152, abbr: 'IHCUS', clubName: 'Ibizan Hound Club of the United States', name: 'AKC Lure Coursing Trial', startDate: '2026-09-07', endDate: null, city: 'Sorento', state: 'IL', lat: 38.988, lng: -89.570, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 153, abbr: 'IWAGS', clubName: 'Irish Wolfhound Association of the Garden State', name: 'AKC Lure Coursing Trial', startDate: '2026-04-04', endDate: '2026-04-05', city: 'Somerset', state: 'NJ', lat: 40.498, lng: -74.487, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 154, abbr: 'IWALE', clubName: 'Irish Wolfhound Association of Lake Erie', name: 'AKC Lure Coursing Trial', startDate: '2026-06-27', endDate: '2026-06-28', city: 'Fredonia', state: 'NY', lat: 42.441, lng: -79.335, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 155, abbr: 'IWALE', clubName: 'Irish Wolfhound Association of Lake Erie', name: 'AKC Lure Coursing Trial', startDate: '2026-10-31', endDate: '2026-11-01', city: 'Fredonia', state: 'NY', lat: 42.441, lng: -79.335, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 156, abbr: 'LOBO', clubName: 'Lobo Lure Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-21', endDate: '2026-03-22', city: 'Santa Fe', state: 'NM', lat: 35.687, lng: -105.938, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 157, abbr: 'LVCC', clubName: 'Lehigh Valley Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-02', endDate: '2026-05-03', city: 'Lambertville', state: 'NJ', lat: 40.366, lng: -74.943, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 158, abbr: 'LVCC', clubName: 'Lehigh Valley Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-06-06', endDate: '2026-06-07', city: 'Lambertville', state: 'NJ', lat: 40.366, lng: -74.943, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 159, abbr: 'LVCC', clubName: 'Lehigh Valley Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-11-21', endDate: '2026-11-22', city: 'Lambertville', state: 'NJ', lat: 40.366, lng: -74.943, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 160, abbr: 'MBC', clubName: 'Midwest Borzoi Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Lima', state: 'OH', lat: 40.742, lng: -84.105, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 161, abbr: 'MCA', clubName: 'Minnesota Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-04-25', endDate: '2026-04-26', city: 'Farmington', state: 'MN', lat: 44.647, lng: -93.149, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 162, abbr: 'MDIHC', clubName: 'Mason-Dixon Ibizan Hound Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-23', endDate: '2026-05-25', city: 'Hanover', state: 'PA', lat: 39.801, lng: -76.984, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 163, abbr: 'MGA', clubName: 'Michigan Gazehound Association', name: 'AKC Lure Coursing Trial', startDate: '2026-06-06', endDate: '2026-06-07', city: 'Bellevue', state: 'MI', lat: 42.244, lng: -85.015, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 164, abbr: 'MGA', clubName: 'Michigan Gazehound Association', name: 'AKC Lure Coursing Trial', startDate: '2026-06-26', endDate: '2026-06-28', city: 'Williamston', state: 'MI', lat: 42.685, lng: -84.282, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 165, abbr: 'MWCC', clubName: 'Midwest Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-06-20', endDate: '2026-06-21', city: 'Caledonia', state: 'WI', lat: 42.786, lng: -87.866, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 166, abbr: 'NCIWC', clubName: 'Northern California Irish Wolfhound Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-01', endDate: null, city: 'Fairfield', state: 'CA', lat: 38.249, lng: -122.040, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 167, abbr: 'NCIWC', clubName: 'Northern California Irish Wolfhound Club', name: 'AKC Lure Coursing Trial', startDate: '2026-10-11', endDate: null, city: 'Woodland', state: 'CA', lat: 38.679, lng: -121.773, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 168, abbr: 'NCWFA', clubName: 'Northern California Whippet Fanciers Association', name: 'AKC Lure Coursing Trial', startDate: '2026-01-10', endDate: '2026-01-11', city: 'Elverta', state: 'CA', lat: 38.714, lng: -121.407, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 169, abbr: 'NTSC', clubName: 'North Texas Saluki Club', name: 'AKC Lure Coursing Trial', startDate: '2026-01-18', endDate: null, city: 'Celina', state: 'TX', lat: 33.300, lng: -96.778, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 170, abbr: 'NWRRC', clubName: 'Northwest Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Ethel', state: 'WA', lat: 46.520, lng: -122.350, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 171, abbr: 'NWRRC', clubName: 'Northwest Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-06-06', endDate: '2026-06-07', city: 'Ethel', state: 'WA', lat: 46.520, lng: -122.350, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 172, abbr: 'NWRRC', clubName: 'Northwest Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-07-11', endDate: '2026-07-12', city: 'Duvall', state: 'WA', lat: 47.742, lng: -121.984, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 173, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-02-14', endDate: '2026-02-15', city: 'Chino', state: 'CA', lat: 33.978, lng: -117.688, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 174, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-04-09', endDate: null, city: 'Chino', state: 'CA', lat: 33.978, lng: -117.688, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 175, abbr: 'OCRRC', clubName: 'Orange Coast Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-30', endDate: '2026-05-31', city: 'Chino', state: 'CA', lat: 33.978, lng: -117.688, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 176, abbr: 'OKIGO', clubName: 'Ohio, Kentucky, Indiana Gazehound Organization', name: 'AKC Lure Coursing Trial', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Fairborn', state: 'OH', lat: 39.831, lng: -84.019, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 177, abbr: 'ORCA', clubName: 'Oklahoma Racing & Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 178, abbr: 'ORCA', clubName: 'Oklahoma Racing & Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-09-26', endDate: '2026-09-27', city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 179, abbr: 'ORCA', clubName: 'Oklahoma Racing & Coursing Association', name: 'AKC Lure Coursing Trial', startDate: '2026-12-05', endDate: null, city: 'Vinita', state: 'OK', lat: 36.636, lng: -95.154, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 180, abbr: 'PHCA', clubName: 'Pharaoh Hound Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-07-12', endDate: null, city: 'Bennett', state: 'CO', lat: 39.751, lng: -104.431, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 181, abbr: 'RMHAC', clubName: 'Rocky Mountain Hound Association of Colorado', name: 'AKC Lure Coursing Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Peyton', state: 'CO', lat: 38.933, lng: -104.298, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 182, abbr: 'RRCUS', clubName: 'Rhodesian Ridgeback Club of the United States', name: 'AKC Lure Coursing Trial', startDate: '2026-10-17', endDate: null, city: "Lee's Summit", state: 'MO', lat: 38.910, lng: -94.382, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 183, abbr: 'SANE', clubName: 'Saluki Association of New England', name: 'AKC Lure Coursing Trial', startDate: '2026-09-26', endDate: '2026-09-27', city: 'Blandford', state: 'MA', lat: 42.149, lng: -72.944, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 184, abbr: 'SCIHC', clubName: 'Southern California Ibizan Hound Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Helena', state: 'MT', lat: 46.596, lng: -112.027, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 185, abbr: 'SCOA', clubName: 'Saluki Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-06-01', endDate: '2026-06-02', city: 'Gray Summit', state: 'MO', lat: 38.421, lng: -90.764, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 186, abbr: 'SDCA', clubName: 'Scottish Deerhound Club of America', name: 'AKC Lure Coursing Trial', startDate: '2026-05-09', endDate: '2026-05-10', city: 'Rockwood', state: 'PA', lat: 39.907, lng: -79.162, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 187, abbr: 'SHOT', clubName: 'Sighthound Organization of Tidewater', name: 'AKC Lure Coursing Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'Dendron', state: 'VA', lat: 37.048, lng: -76.950, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 188, abbr: 'SSIH', clubName: 'Sierra Slopes Ibizan Hounds', name: 'AKC Lure Coursing Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Elverta', state: 'CA', lat: 38.714, lng: -121.407, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 189, abbr: 'SSRRC', clubName: 'Sunshine State Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-01-03', endDate: '2026-01-04', city: 'Weirsdale', state: 'FL', lat: 29.054, lng: -81.930, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 190, abbr: 'SSRRC', clubName: 'Sunshine State Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-02-07', endDate: '2026-02-08', city: 'High Springs', state: 'FL', lat: 29.832, lng: -82.598, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 191, abbr: 'SSRRC', clubName: 'Sunshine State Rhodesian Ridgeback Club', name: 'AKC Lure Coursing Trial', startDate: '2026-03-28', endDate: '2026-03-29', city: 'Weirsdale', state: 'FL', lat: 29.054, lng: -81.930, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 192, abbr: 'THLC', clubName: 'Tortoise & Hare Lure Coursers', name: 'AKC Lure Coursing Trial', startDate: '2026-06-13', endDate: '2026-06-14', city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 193, abbr: 'THLC', clubName: 'Tortoise & Hare Lure Coursers', name: 'AKC Lure Coursing Trial', startDate: '2026-10-03', endDate: '2026-10-04', city: 'Littlestown', state: 'PA', lat: 39.741, lng: -76.930, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 194, abbr: 'TVRRCT', clubName: 'Trinity Valley Rhodesian Ridgeback Club of Texas', name: 'AKC Lure Coursing Trial', startDate: '2026-04-11', endDate: '2026-04-12', city: 'Ponder', state: 'TX', lat: 33.177, lng: -97.276, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 195, abbr: 'TVRRCT', clubName: 'Trinity Valley Rhodesian Ridgeback Club of Texas', name: 'AKC Lure Coursing Trial', startDate: '2026-05-16', endDate: '2026-05-17', city: 'McKinney', state: 'TX', lat: 33.197, lng: -96.615, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 196, abbr: 'TVRRCT', clubName: 'Trinity Valley Rhodesian Ridgeback Club of Texas', name: 'AKC Lure Coursing Trial', startDate: '2026-11-07', endDate: '2026-11-08', city: 'McKinney', state: 'TX', lat: 33.197, lng: -96.615, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 197, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-04-18', endDate: '2026-04-19', city: 'South Jordan', state: 'UT', lat: 40.560, lng: -111.929, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 198, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-05-17', endDate: null, city: 'Hyde Park', state: 'UT', lat: 41.794, lng: -111.817, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 199, abbr: 'USRCC', clubName: 'Utah Sighthound Racing & Coursing Club', name: 'AKC Lure Coursing Trial', startDate: '2026-10-17', endDate: '2026-10-18', city: 'Hyde Park', state: 'UT', lat: 41.794, lng: -111.817, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 200, abbr: 'WWHA', clubName: 'Western Washington Hound Association', name: 'AKC Lure Coursing Trial', startDate: '2026-04-18', endDate: '2026-04-19', city: 'Ethel', state: 'WA', lat: 46.520, lng: -122.350, org: 'AKC', isSpecialty: false, isCancelled: false },
  { id: 201, abbr: 'WWWA', clubName: 'Western Washington Whippet Association', name: 'AKC Lure Coursing Trial', startDate: '2026-06-20', endDate: '2026-06-21', city: 'Monroe', state: 'WA', lat: 47.855, lng: -121.971, org: 'AKC', isSpecialty: false, isCancelled: false },
];
